name: GVFITNESS Backend CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test
        
  deploy:
      uses: ./.github/workflows/deploy.yml
      if: github.ref == 'refs/heads/main'
      needs: build
      with:
        service-port: 5000
      secrets:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        