on:
  workflow_call:
    inputs:
      service-port:
          type: string
          default: "5000"
      secrets:
        VERCEL_TOKEN:
          required: true
        MONGO_URI:
          required: true

jobs:
  deploy_to_vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Install vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel pull --yes --environment=preview --token="${{ secrets.VERCEL_TOKEN }}"
          vercel build --token="${{ secrets.VERCEL_TOKEN }}"
          vercel deploy --prod --yes --token="${{ secrets.VERCEL_TOKEN }}" \
            -e PORT="${{ inputs.service-port }}" \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \